-- MySQL Script generated by MySQL Workbench
-- Sat May  4 11:48:28 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema filestore
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `filestore` ;

-- -----------------------------------------------------
-- Schema filestore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `filestore` DEFAULT CHARACTER SET utf8 ;
USE `filestore` ;

-- -----------------------------------------------------
-- Table `filestore`.`files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `filestore`.`files` ;

CREATE TABLE IF NOT EXISTS `filestore`.`files` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `md5` VARCHAR(32) NOT NULL,
  `length` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
  `position` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `md5_UNIQUE` (`md5` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `filestore`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `filestore`.`users` ;

CREATE TABLE IF NOT EXISTS `filestore`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `filestore`.`user_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `filestore`.`user_files` ;

CREATE TABLE IF NOT EXISTS `filestore`.`user_files` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `file_id` INT(11) NOT NULL,
  `filename` VARCHAR(90) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`user_id` ASC) ,
  INDEX `file_idx` (`file_id` ASC) ,
  CONSTRAINT `file`
    FOREIGN KEY (`file_id`)
    REFERENCES `filestore`.`files` (`id`),
  CONSTRAINT `user`
    FOREIGN KEY (`user_id`)
    REFERENCES `filestore`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;

USE `filestore` ;

-- -----------------------------------------------------
-- Placeholder table for view `filestore`.`files_of_user_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filestore`.`files_of_user_view` (`file_id` INT, `user_id` INT, `fileName` INT, `md5` INT, `fullLength` INT, `currentLenght` INT);

-- -----------------------------------------------------
-- View `filestore`.`files_of_user_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `filestore`.`files_of_user_view`;
DROP VIEW IF EXISTS `filestore`.`files_of_user_view` ;
USE `filestore`;
CREATE  OR REPLACE VIEW `files_of_user_view` AS
SELECT 
  user_files.user_id AS user_id,
  user_files.filename AS fileName,
  files.md5 AS md5,
  files.length AS fullLength,
  files.position AS currentLength
FROM user_files, users, files 
WHERE user_files.user_id=users.id AND user_files.file_id=files.id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
